// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movingconfirmationforliststhatcanbeemptyandcompletetolicenselevelalsomovingoptoutstolicenselevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movingconfirmationforliststhatcanbeemptyandcompletetolicenselevelalsomovingoptoutstolicenselevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201702032130538_moving confirmation for lists that can be empty and complete to license level, also moving optouts to license level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
