// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movingSwitchableLicenseTypefromLicensetoLicenseType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movingSwitchableLicenseTypefromLicensetoLicenseType));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151759455_moving SwitchableLicenseType from License to LicenseType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
