// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingpaymentsandtyingtolicense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingpaymentsandtyingtolicense));
        
        string IMigrationMetadata.Id
        {
            get { return "201704282108075_adding payments and tying to license"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
