// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingphonenumberpartsto1fieldandaddingextension : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingphonenumberpartsto1fieldandaddingextension));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132225317_changing phone number parts to 1 field and adding extension"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
