// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movingdonationsconfirmationtoLicenselevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movingdonationsconfirmationtoLicenselevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201702071909594_moving donations confirmation to License level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
