// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingAmsSequenceNumbertoProfessionalLiabilityInsurance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingAmsSequenceNumbertoProfessionalLiabilityInsurance));
        
        string IMigrationMetadata.Id
        {
            get { return "201704172126497_adding AmsSequenceNumber to ProfessionalLiabilityInsurance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
