// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actuallyadmissiondatesshouldntbenullable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actuallyadmissiondatesshouldntbenullable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704272102209_actually, admission dates shouldn't be nullable 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
