// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removingkellerdeductionpercentagefromlicensetypeaddingkellerdiscounttableaddingrelationshiptolicensetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingkellerdeductionpercentagefromlicensetypeaddingkellerdiscounttableaddingrelationshiptolicensetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201706011924584_removing keller deduction percentage from license type, adding keller discount table, adding relationship to license type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
