// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removingnullablesonprobono2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingnullablesonprobono2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702102327596_removing nullables on probono 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
