// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingkellerdeductionandhardshipexemptiontorequirementslicensefeeexempttolicensekellerdeductionpercentagetolicensetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingkellerdeductionandhardshipexemptiontorequirementslicensefeeexempttolicensekellerdeductionpercentagetolicensetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201705311822557_adding keller deduction and hardship exemption to requirements, license fee exempt to license, keller deduction percentage to license type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
