// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingDiscountPercentageprecisiontoallow4decimalplacesonKellerDiscount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingDiscountPercentageprecisiontoallow4decimalplacesonKellerDiscount));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051914402_changing DiscountPercentage precision to allow 4 decimal places on KellerDiscount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
