// <auto-generated />
namespace Licensing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingphoneandaddresscountryandstates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingphoneandaddresscountryandstates));
        
        string IMigrationMetadata.Id
        {
            get { return "201703131726069_adding phone and address country and states"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
